name: Build and Deploy Telegram Bot

# Bu workflow yalnızca manuel olarak tetiklenecek
on:
  workflow_dispatch:  # Manuel tetikleme
    inputs:
      deployment:
        description: 'Do you want to deploy the bot?'
        required: true
        default: 'no'

jobs:
  build:
    runs-on: ubuntu-latest  # Workflow, Ubuntu ortamında çalışacak

    steps:
      # 1. Kodu Çekme
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Python ve Bağımlılıkları Kurma
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3. Testleri Çalıştırma (Opsiyonel)
      - name: Run tests
        run: |
          pytest  # Eğer testleriniz varsa, burada çalıştırılacak

      # Docker imajını otomatik olarak oluşturma ve konteyneri çalıştırma işlemi iptal edilmiştir
      # - name: Build Docker image
      #   run: |
      #     docker build -t telegram-bot .

      # - name: Run Docker container
      #   run: |
      #     docker run -d --name telegram-bot-container telegram-bot

      # Eğer veritabanı yedekleme yapmak isterseniz, aşağıdaki gibi bir adım ekleyebilirsiniz
      # - name: Backup Database
      #   run: |
      #     docker exec telegram-bot-container cp /app/database.db /backups/database-backup.db

      # 4. Dağıtım (Opsiyonel)
      # Eğer deployment yapmanız gerekirse, bu adımı ekleyebilirsiniz
      # - name: Deploy to production
      #   run: |
      #     docker-compose down  # Eski konteyneri durdurma
      #     docker-compose up -d  # Yeni konteyneri başlatma
